### ISSUE TITLE
13 seconds are enough :P

### ISSUE THREAD

**Issue by oddcoder** [louay-hesham/ssp_helper#2]
During 13 seconds it was possible to

1- tell the project was hosted on github,
2- and this is not official alexandria university app
3- and it is just for enumerating possible options
4- it may not be up to date :package: 

8ayar ba2a el timer le 13 seconds :rofl: 

![image](https://user-images.githubusercontent.com/10424605/50847565-9946c280-137a-11e9-9060-58644b8c3c65.png)

**Comment by louay-hesham** [comment]
lol
I will keep it at 20 seconds as it is. Not everyone is a fast reader like you. Plus I'm too lazy to change it anyway, at least for now :smile: 

You don't have to wait each time you open the website, a cookie is created after the first time indicating that you've already read the disclaimer. So afterwards you can proceed right away without waiting for 20 seconds.
