### ISSUE TITLE
courses selection bug

### ISSUE THREAD

**Issue by MAE999** [louay-hesham/ssp_helper#3]
after selection of the department, then highlightig the course the popup menu of department keep swithing without selecting any courses and this term button dont work too

**Comment by louay-hesham** [comment]
The departments dropdown menu was staying active but invisible. Fixed by using Angular's built-in dropdown menu API [in the latest commit](https://github.com/louay-hesham/ssp_helper/commit/57ddc4c3847ae330d5746aea162c8272095a0708)
