### ISSUE TITLE
the same bug isnt fixed

### ISSUE THREAD

**Issue by MAE999** [louay-hesham/ssp_helper#4]
i cant acess my electromechanical courses,
note:i use firefox browser

**Comment by louay-hesham** [comment]
Can you post a screenshot of what you see? It's working on my side.

**Comment by MAE999** [comment]
![image](https://user-images.githubusercontent.com/66372417/99186786-641c1000-275b-11eb-8e9c-ea37034732d0.png)
when i click on the pop up menu and choos my department then begin to choose the courses the department pop up menu keep changing value when i click anywhere

**Comment by louay-hesham** [comment]
Your device is probably using an older cached version of the website. This is how it should look.
![Screenshot from 2020-11-15 18-12-25](https://user-images.githubusercontent.com/16453423/99191637-3096b100-276e-11eb-88c7-fb5a8085720c.png)
Notice the different theme of the dropdown button?

Try doing a hard refresh (ctrl+shift+R), or right click on the refresh button then choose hard reload. Please tell me afterwards whether this resolved the issue or not.

**Comment by MAE999** [comment]
worked like a charm, thanks
